### ISSUE TITLE
Umeå utegym som öppna data med koppling Wikidata

### ISSUE THREAD

**Issue by salgo60** [salgo60/ProjectOutdoorGyms#124]
Maria Söderlund skriver [länk](https://community.dataportal.se/topic/454/hur-vill-ni-som-anv%C3%A4nder-datam%C3%A4ngder-kunna-bidra-med-wikidata-q-koden/31?_=1674225524792)

<img width="877" alt="image" src="https://user-images.githubusercontent.com/14206509/213725313-5de5c193-11d1-42f6-a91f-ac321bab3c01.png">

----
**Export och koppla WIkidata**
* [länk](https://opendata.umea.se/explore/dataset/utegym-umea/wikidata/?sort=id#sv)

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/14206509/213727534-11bfd6f2-dbbc-420b-8dfb-a8d04262e0d7.png">

**Comment by salgo60** [comment]
1. Hämta datat och skapa samma som WIkidata med [Open refine](https://openrefine.org/)
2. Skapa ett objekt för dataset Utegym jmf [dataset konstverk](https://www.wikidata.org/wiki/Special:WhatLinksHere/Q102343039?uselang=sv) - [alla](https://w.wiki/6F7h) 
   1. det vi gjorde med konstverk Umeå [T268797](https://phabricator.wikimedia.org/T268797)
4. Skapa ny koppling Wikidata -> Umeå data set och kopplar det på inventarienummer egenskap P217 i brist på bättre
5. Skapa poster i Google Map för alla utegymen eller koppla ihop med Wikidata om de redan finns
6. Skapa poster i Open Street Map
7. Ladda upp skapat fil till Umeå portalen
8. Skapa en Notebook modell som för Stockholm så vi kan enkelt kolla diff #99 

----
**Open Street Map**
* bild nedan läst in datasetet och ser att några objekt saknas i Wikidata
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/14206509/213729276-688fc134-3846-43a3-b4b1-9d277f464b40.png">

----
**Wikidata**
Skapar ett WD objekt för datasetet utegym [Q116268026](https://www.wikidata.org/wiki/Q116268026?uselang=sv)

--> att varje utegym får egenskap P217 som pekar på Umeå kommuns dataset --> att vi enkelt kan skapa en Notebook och jmf se #99

<img width="979" alt="image" src="https://user-images.githubusercontent.com/14206509/213730695-1850121a-41b0-4c1d-a741-c595321c6791.png">

**Comment by salgo60** [comment]
* [karta Wikidata utegym](https://w.wiki/6FAG)

**Comment by dpriskorn** [comment]
Jag tycker vi ska vänta med notebook tills vi ser att de faktiskt klarar av att iterera och förbättra över tid

**Comment by salgo60** [comment]
> Har de unika id? Om inte så kan de ju själva hitta qid via din karta ovan

Notebook blir samma som för Stockholm dvs, att se till att vi har alla utegym #99 
* fördelen med Stockholm är att dom har 10% av alla Sveriges utegym...

**Unika ID**: japp jag har gjort en fuling för Stockholm och Umeå och några andra och lagt det i P217 [se karta](https://w.wiki/6FgM)

**Comment by salgo60** [comment]
* [Notebook](https://github.com/salgo60/ProjectOutdoorGyms/blob/main/Jupyter/Ume%C3%A5%20outdoor%20gym.ipynb) --> [list ume id WD](https://github.com/salgo60/ProjectOutdoorGyms/blob/main/Jupyter/Ume_data_WD.csv) - [raw](https://raw.githubusercontent.com/salgo60/ProjectOutdoorGyms/main/Jupyter/Ume_data_WD.csv)
0	None	Q107656895
1	None	Q107656909
2	2480_BrantbergetUtegym	Q107248603
3	2480_OstraSocionomparkenutegym	Q107248498
4	None	Q107248525
5	2480_BettnessandUtegym	Q107248559
6	None	Q107259161
7	2480_Ersbodaaventyrslekutegym	Q107259289
8	2480_Hedlundadungenutegym	Q107391513
9	2480_SkogsvallensIPUtegym	Q107391519
10	2480_VastraHagaparkenutegym	Q107391537
11	2480_StadslidenUtegym	Q107391541
12	2480_Varvsparkenutegym	Q107391548
13	2480_VastermalmsparkenUtegym	Q107391606
14	None	Q114835989
15	2480_Tomteboaventyrslekutegym	Q116270354
16	2480_AventyrsparkensutegymiRodasel	Q116270356

**Comment by salgo60** [comment]
* [Laddas upp](https://opendata.umea.se/explore/dataset/utegym-umea/wikidata/?sort=id#sv)
