### ISSUE TITLE
Koordinater till utegym i Bollnäs

### ISSUE THREAD

**Issue by salgo60** [salgo60/ProjectOutdoorGyms#8]
**Email**

Hej 

Det är svårt att förstå vilka utegym ni har och var dom finns på sidan utomhusgym 

Skulle vi kunna få  en lista med 
* namn
* koordinat
* websida om det finns

Vi försöker sammanställa alla utegym som finns i WIkipedia se [Wikidata:WikiProject_Outdoor_Gyms](https://www.wikidata.org/wiki/Wikidata:WikiProject_Outdoor_Gyms)

Exempel: [Q107426646](https://www.wikidata.org/wiki/Q107426646) Bollebergets Skidstadion, utegym  

Hlsn
Magnus Sälgö

**Comment by salgo60** [comment]
Hej Magnus!

 

Här kommer koordinater för våra utegym:


Bollebergets Skidstadion
koordinater: 61.37594674231024, 16.347005356016712
Björktjäratjärn
koordinater: 61°21'34.1"N 16°23'05.7"E
Hoberget nära Bollnäs Sporthall och i direkt anslutning till motionsspår
koordinater: 61.35466701066271, 16.374832060315352
Långnäs udde
koordinater: 61.34201029695903, 16.407568782601864
Kilafors
koordinater: 61.22901205784606, 16.568282345285116

Forsön i Arbrå
koordinater: 61.46569223410764, 16.385184003140267
 

 

Allt gott,


Linda Åldal
Kommunikatör

**Comment by dpriskorn** [comment]
Är koordinaterna där CC0?

**Comment by salgo60** [comment]
Det kan man undra....
