### ISSUE TITLE
SY2108242219QOL Vårbergstoppen, utegym saknas på er websida över utegym och i ert Öppna data 

### ISSUE THREAD

**Issue by salgo60** [salgo60/ProjectOutdoorGyms#90]
Felanmält på https://etjanst.stockholm.se/TyckTill/
![image](https://user-images.githubusercontent.com/14206509/130684155-106cfe47-a204-40cb-b34c-43b6eb97dd19.png)

Enligt detta [dokument](https://insynsverige.se/documentHandler.ashx?did=1959565) sid 4
![image](https://user-images.githubusercontent.com/14206509/130683854-4788acfc-70cb-41b5-8ef4-9d59921d616a.png)

och [denna bild](https://www.mitti.se/nyheter/varbergstoppen-snart-helt-oppen-for-lek/repuah!2J2hG@VACxmMIexJdl7EZQ/)
![image](https://user-images.githubusercontent.com/14206509/130681419-d977edf4-261f-4fa5-964e-92cb4f851073.png)

och denna sida 
* websida [Parker och natur Parker Vårbergstoppen](https://parker.stockholm/parker/varbergstoppen/) nämner detta utegym

finnas ett utegym på Vårbergstoppen

**Problem** Info om detta utegym bör finnas med på
* er websida om utegym [motionera.stockholm/hitta-utegym](https://motionera.stockholm/hitta-utegym/)
* i ert Öppna data [länk](https://apigw.stockholm.se/NoAuth/VirtualhittaserviceDMZ/Rest/serviceunits?&filter[servicetype.id]=122)
och gärna med bilder med en fri licens se vidare frågor

Fler frågor finns om öppna data
* Hur licenser på bilder hanteras  https://github.com/salgo60/ProjectOutdoorGyms/issues/74
* Hur planerade utegym skall hittas https://github.com/salgo60/ProjectOutdoorGyms/issues/88

**Comment by salgo60** [comment]
![image](https://user-images.githubusercontent.com/14206509/132015035-7a39f268-629b-42d7-b505-936998be62ec.png)

**Comment by salgo60** [comment]
Status 2021-11-03
* web 85 utegym
* [API](https://apigw.stockholm.se/NoAuth/VirtualhittaserviceDMZ/Rest/serviceunits?&filter\x5Bservicetype.id\x5D=122&sort=name) 
* nytt utegym websidan
   * [Lilla Blecktornsparkens utegym](https://motionera.stockholm/hitta-utegym/utegym/lilla-blecktornsparkens-utegym/)
   *

**Comment by salgo60** [comment]
Status 2022 05 10
* finns sida på web:en [hitta-utegym/utegym/varbergstoppens-utegym/](https://motionera.stockholm/hitta-utegym/utegym/varbergstoppens-utegym/)
* API [service typ 122](https://apigw.stockholm.se/NoAuth/VirtualhittaserviceDMZ/Rest/serviceunits?&filter[servicetype.id]=122&page[limit]=1500&page[offset]=0&sort=name)

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/14206509/167618073-bd1eaee9-8927-4877-95d0-144fe5af304d.png">

**Comment by dpriskorn** [comment]
Fixade de felet i URL formatet?

**Comment by salgo60** [comment]
@dpriskorn tror vi har en monolog ;-) 

Lite kul nu med skolor över tid se https://github.com/Riksarkivet/dataplattform/issues/1
